version: "3"

services:
  dev-frontend:
    build: .
    image: "threshold/dev-frontend:${TAG:-unknown}"
    ports:
      - 80:80
    environment:
      # Optional Infura API key to enable snappier blockchain events using WebSockets
      - INFURA_API_KEY=
    restart: always
